### ISSUE TITLE
Thanks for sharing!

### ISSUE THREAD

**Issue by jwillmer** [Lillifee/espbs#1]
The air quality IoT and the e-ink monitor design are very cool. Will probably build them as well.

In case you are using Zigbee in your home you can have a look at my [case for a Zigbee MQTT gateway](https://www.prusaprinters.org/prints/37100-tiny-raspberry-pi-zero-case-with-antenna). I can also recommend the Xiaomi Temperature Humidity Sensors. They are pretty cheap & reliable and you can connect them to the Zigbee gateway without any problems.

**Comment by Lillifee** [comment]
Thanks a lot!!

I'm currently using loxone as a home automation server, but I still have a raspberry4 lying around, waiting for some home automation action. But until now, I could manage everything without additional raspberry. The temperature measurements are covered through my light switches, but maybe I should give the Xiaomi aquaria door contacts a try. 🤔  What else do you connect over Zigbee?

I like the block optic of your case! How do the thin lines between the blocks turn out? 

Let me know if you have trouble setting up everything. I still need to clean up the project and improve some parts but unfortunately, I'm not the best arduino/c developer 🙄

**Comment by jwillmer** [comment]
The Xiaomi door contacts are awesome. They work flawlessly for the last 2 years without changing the battery. I have installed one at my balcony door. I bought the Xiaomi home automation "starter kit" and some additional temp/hum sensors and connected all to the Zigbee Gateway - and threw away the Xiaomi Gateway.

The case lines are working nicely. I was a bit disappointed from the case at first since I printed with .2mm and it looked pretty rough. But when it sits on the wall and you are a meter away it looks really nice. If you like to print it, I would propose to add some kind of hinge to the antenna end since you can see a 1-2mm gap when you tighten the mounting screw - when again, only if inspection from close range.

Take your time with the project. It's anyway never finished. Useful parts will improve, others will degrade. At the end it needs to solve your headaches :sunglasses: I have just subscribed to the changes so I keep an eye on it and when time comes I will try to use some parts of it in my home setup.
